// Space
export const SpaceFormat = {
  POLITICAL_MOBILIZATION: "POLITICAL_MOBILIZATION",
  COMMERCIAL_ADS: "COMMERCIAL_ADS",
  SOCIALIZATION: "SOCIALIZATION",
};

export const SpaceType = {
  PUBLIC_LAND: "PUBLIC_LAND",
  PARK: "PARK",
  TRAFFIC_CORRIDOR: "TRAFFIC_CORRIDOR",
  PRIVATE_LAND: "PRIVATE_LAND",
  SHOPPING_CENTER: "SHOPPING_CENTER",
  MARKET: "MARKET",
  GAS_STATION: "GAS_STATION",
  BUS_SHELTER: "BUS_SHELTER",
};

export const RequestState = {
  IN_PROGRESS: "IN_PROGRESS",
  REJECTED: "REJECTED",
  APPROVED: "APPROVED",
  CANCELED: "CANCELED",
};

// Surface
export const SurfaceFormat = {
  HIFLEX_POST: "HIFLEX_POST",
  LED_SCREEN: "LED_SCREEN",
  LIGHT_BOX: "LIGHT_BOX",
  HIFLEX_WALL: "HIFLEX_WALL",
  WALL_MOUNTED_LED_SCREEN: "WALL_MOUNTED_LED_SCREEN",
  VERTICAL_BANNER: "VERTICAL_BANNER",
  HORIZONTAL_BANNER: "HORIZONTAL_BANNER",
  PANEL: "PANEL",
  WELCOME_GATE: "WELCOME_GATE",
  SHOPPING_CENTER: "SHOPPING_CENTER",
};

// Report
export const ReportState = {
  IN_PROGRESS: "IN_PROGRESS",
  REJECTED: "REJECTED",
  APPROVED: "APPROVED",
};

//User
export const UserRole = {
  WARD_ADMIN: "WARD_ADMIN",
  DISTRICT_ADMIN: "DISTRICT_ADMIN",
  ADMIN: "ADMIN",
};

//Form Mode
export const FormMode = {
  CREATE: "CREATE",
  EDIT: "EDIT",
};

//User
export const Role = {
  WARD_ADMIN: "WARD_ADMIN",
  DISTRICT_ADMIN: "DISTRICT_ADMIN",
  ADMIN: "ADMIN",
};
